require("lunit")
local Array = require("collection/array")

describe("Array", function()
    describe("constructor", function()
        it("creates an empty array if no length is provided", function()
            local a = Array:new()
            expect(a).to.have.a.property("length", 0)
            expect(a:toSeq()).to.deep.equal({})
        end)
    end)
    describe("[]", function()
        it("can be used for indexing arrays", function()
            local a = Array:of("a", nil, "c")
            expect(a).to.have.a.property("length", 3)
            expect(a).to.have.a.property(1, "a")
            expect(a).to._not_.have.a.property(2)
            expect(a).to.have.a.property(3, "c")
        end)
        it("can be used for setting elements with an index", function()
            local a = Array:new()
            a[2] = "b"
            expect(a).to.have.a.property("length", 2)
            expect(a).to._not_.have.a.property(1)
            expect(a).to.have.a.property(2, "b")
        end)
    end)
    describe("..", function()
        it("concatenates two arrays", function()
            local a1 = Array:of("a", nil)
            local a2 = Array:of("c")
            local a  = a1 .. a2
            expect(a).to.have.a.property("length", 3)
            expect(a).to.have.a.property(1, "a")
            expect(a).to._not_.have.a.property(2)
            expect(a).to.have.a.property(3, "c")
        end)
    end)
    describe(":splice()", function()
        it("works correctly when nDelete > nInsert", function()
            local a = Array:of(10, 20, nil, 40, 50, 60, 70, 80)
            local d = a:splice(3, 2, "a")
            expect(a).to.deep.equal(Array:of(10, 20, "a", 50, 60, 70, 80))
            expect(d).to.deep.equal(Array:of(nil, 40))
        end)
        it("works correctly when nDelete == nInsert", function()
            local a = Array:of(10, 20, nil, 40, 50, 60, 70, 80)
            local d = a:splice(3, 2, "a", "b")
            expect(a).to.deep.equal(Array:of(10, 20, "a", "b", 50, 60, 70, 80))
            expect(d).to.deep.equal(Array:of(nil, 40))
        end)
        it("works correctly when nDelete < nInsert", function()
            local a = Array:of(10, 20, nil, 40, 50, 60, 70, 80)
            local d = a:splice(3, 2, "a", "b", "c")
            expect(a).to.deep.equal(Array:of(10, 20, "a", "b", "c", 50, 60, 70, 80))
            expect(d).to.deep.equal(Array:of(nil, 40))
        end)
    end)
    describe(":entries()", function()
        it("returns an iterator that is similar to what ipairs() returns", function()
            local ents = {}
            for i, elem in Array:of("a", nil, "c"):entries() do
                table.insert(ents, {i, elem})
            end
            expect(ents).to.deep.equal({
                {1, "a"},
                {2, nil},
                {3, "c"}
            })
        end)
    end)
    describe(":values()", function()
        it("returns an iterator that iterates over non-nil elements", function()
            local vals = {}
            for elem in Array:of("a", nil, "c"):values() do
                table.insert(vals, elem)
            end
            expect(vals).to.deep.equal({"a", "c"})
        end)
    end)
    describe(":toSeq()", function()
        it("converts an array into a sequence if it's not sparse", function()
            local a = Array:of("a", "b", "c")
            expect(a:toSeq()).to.deep.equal({"a", "b", "c"})
        end)
        it("raises an error if the array is sparse", function()
            local a = Array:of("a", nil, "c")
            expect(function() a:toSeq() end).to.throw()
        end)
    end)
    describe(":unpack()", function()
        it("behaves like table.unpack(seq, 1, #seq)", function()
            local a = Array:of("a", nil, "c")
            local function get(...)
                local args, nArgs = {...}, select("#", ...)
                expect(nArgs).to.equal(3)
                expect(args[1]).to.equal("a")
                expect(args[2]).to.be.null()
                expect(args[3]).to.equal("c")
            end
            get(a:unpack())
        end)
    end)
    describe("tostring()", function()
        it("reasonably stringifies an array", function()
            local a = Array:of(1, nil, 3)
            expect(tostring(a)).to.equal("Array {1, nil, 3}")
        end)
    end)
end)
