require("lunit")
local path = require("path")

describe("path", function()
    describe(".sep", function()
        it("is a platform-dependent path separator", function()
            expect(path.posix  .sep).to.equal("/")
            expect(path.windows.sep).to.equal("\\")

            expect(path.sep).to.match("[/\\]")
        end)
    end)
    describe(".dirname()", function()
        it("extracts the directory part of a path", function()
            expect(path.posix.dirname("foo/bar"  )).to.equal("foo")
            expect(path.posix.dirname("foo/bar/" )).to.equal("foo")
            expect(path.posix.dirname("foo"      )).to.equal(".")
            expect(path.posix.dirname(""         )).to.equal(".")
            expect(path.posix.dirname("/foo/bar" )).to.equal("/foo")
            expect(path.posix.dirname("/foo/bar/")).to.equal("/foo")
            expect(path.posix.dirname("/foo"     )).to.equal("/")
            expect(path.posix.dirname("/"        )).to.equal("/")

            expect(path.windows.dirname("foo\\bar"      )).to.equal("foo")
            expect(path.windows.dirname("foo/bar"       )).to.equal("foo")
            expect(path.windows.dirname("foo\\bar\\"    )).to.equal("foo")
            expect(path.windows.dirname("foo/bar/"      )).to.equal("foo")
            expect(path.windows.dirname("foo"           )).to.equal(".")
            expect(path.windows.dirname(""              )).to.equal(".")
            expect(path.windows.dirname("C:\\foo\\bar"  )).to.equal("C:\\foo")
            expect(path.windows.dirname("C:\\foo\\bar\\")).to.equal("C:\\foo")
            expect(path.windows.dirname("C:\\foo"       )).to.equal("C:\\")
            expect(path.windows.dirname("C:\\"          )).to.equal("C:\\")
            expect(path.windows.dirname("\\\\host\\root\\foo\\bar"  )).to.equal("\\\\host\\root\\foo")
            expect(path.windows.dirname("\\\\host\\root\\foo\\bar\\")).to.equal("\\\\host\\root\\foo")
            expect(path.windows.dirname("\\\\host\\root\\foo"       )).to.equal("\\\\host\\root\\")
            expect(path.windows.dirname("\\\\host\\root\\"          )).to.equal("\\\\host\\root\\")
            expect(path.windows.dirname("\\\\host\\root"            )).to.equal("\\\\host\\root")
            expect(path.windows.dirname("\\\\host\\"                )).to.equal("\\\\host\\")

            expect(path.dirname("foo/bar")).to.equal("foo")
        end)
    end)
    describe(".join()", function()
        it("joins all given path segments together", function()
            expect(path.posix  .join("foo", "bar", "baz")).to.equal("foo/bar/baz")
            expect(path.windows.join("foo", "bar", "baz")).to.equal("foo\\bar\\baz")

            expect(path.join("foo", "bar", "baz")).to.be.oneOf(
                {"foo/bar/baz", "foo\\bar\\baz"})
        end)
    end)
    -- path.resolve() is unfortunately not testable.
end)
