require("lunit")
local path = require("path")

describe("path", function()
    describe(".sep", function()
        it("is a platform-dependent path separator", function()
            expect(path.posix  .sep).to.equal("/")
            expect(path.windows.sep).to.equal("\\")

            expect(path.sep).to.match("[/\\\\]")
        end)
    end)
    describe(".basename()", function()
        it("extracts the file part of a path", function()
            expect(path.posix.basename("foo/bar" )).to.equal("bar")
            expect(path.posix.basename("foo/bar/")).to.equal("bar")
            expect(path.posix.basename("foo/"    )).to.equal("foo")
            expect(path.posix.basename("foo"     )).to.equal("foo")
            expect(path.posix.basename("/"       )).to.equal("")

            expect(path.windows.basename("foo\\bar"  )).to.equal("bar")
            expect(path.windows.basename("foo/bar"   )).to.equal("bar")
            expect(path.windows.basename("foo\\bar\\")).to.equal("bar")
            expect(path.windows.basename("foo/bar/"  )).to.equal("bar")
            expect(path.windows.basename("foo\\"     )).to.equal("foo")
            expect(path.windows.basename("foo/"      )).to.equal("foo")
            expect(path.windows.basename("foo"       )).to.equal("foo")
            expect(path.windows.basename("\\"        )).to.equal("")
            expect(path.windows.basename("C:\\"      )).to.equal("")
            expect(path.windows.basename("C:"        )).to.equal("")

            expect(path.basename("foo/bar")).to.equal("bar")
        end)
        it("optionally strips a suffix off", function()
            expect(path.posix.basename("foo/bar.gz", ".gz"   )).to.equal("bar")
            expect(path.posix.basename("foo/bar.gz", ".zip"  )).to.equal("bar.gz")
            expect(path.posix.basename("foo/bar.gz", "bar.gz")).to.equal("bar.gz")

            expect(path.windows.basename("foo\\bar.gz", ".gz"   )).to.equal("bar")
            expect(path.windows.basename("foo/bar.gz" , ".gz"   )).to.equal("bar")
            expect(path.windows.basename("foo\\bar.gz", ".zip"  )).to.equal("bar.gz")
            expect(path.windows.basename("foo/bar.gz" , ".zip"  )).to.equal("bar.gz")
            expect(path.windows.basename("foo\\bar.gz", "bar.gz")).to.equal("bar.gz")
            expect(path.windows.basename("foo/bar.gz" , "bar.gz")).to.equal("bar.gz")

            expect(path.basename("foo/bar.gz", ".gz")).to.equal("bar")
        end)
    end)
    describe(".dirname()", function()
        it("extracts the directory part of a path", function()
            expect(path.posix.dirname("foo/bar"  )).to.equal("foo")
            expect(path.posix.dirname("foo/bar/" )).to.equal("foo")
            expect(path.posix.dirname("foo"      )).to.equal(".")
            expect(path.posix.dirname(""         )).to.equal(".")
            expect(path.posix.dirname("/foo/bar" )).to.equal("/foo")
            expect(path.posix.dirname("/foo/bar/")).to.equal("/foo")
            expect(path.posix.dirname("/foo"     )).to.equal("/")
            expect(path.posix.dirname("/"        )).to.equal("/")

            expect(path.windows.dirname("foo\\bar"      )).to.equal("foo")
            expect(path.windows.dirname("foo/bar"       )).to.equal("foo")
            expect(path.windows.dirname("foo\\bar\\"    )).to.equal("foo")
            expect(path.windows.dirname("foo/bar/"      )).to.equal("foo")
            expect(path.windows.dirname("foo"           )).to.equal(".")
            expect(path.windows.dirname(""              )).to.equal(".")
            expect(path.windows.dirname("C:\\foo\\bar"  )).to.equal("C:\\foo")
            expect(path.windows.dirname("C:\\foo\\bar\\")).to.equal("C:\\foo")
            expect(path.windows.dirname("C:\\foo"       )).to.equal("C:\\")
            expect(path.windows.dirname("C:\\"          )).to.equal("C:\\")
            expect(path.windows.dirname("\\\\host\\root\\foo\\bar"  )).to.equal("\\\\host\\root\\foo")
            expect(path.windows.dirname("\\\\host\\root\\foo\\bar\\")).to.equal("\\\\host\\root\\foo")
            expect(path.windows.dirname("\\\\host\\root\\foo"       )).to.equal("\\\\host\\root\\")
            expect(path.windows.dirname("\\\\host\\root\\"          )).to.equal("\\\\host\\root\\")
            expect(path.windows.dirname("\\\\host\\root"            )).to.equal("\\\\host\\root")
            expect(path.windows.dirname("\\\\host\\"                )).to.equal("\\\\host\\")
            -- \\host isn't a valid UNC path on Windows. dirname is not defined for that.

            expect(path.dirname("foo/bar")).to.equal("foo")
        end)
    end)
    describe(".join()", function()
        it("joins all given path segments together", function()
            expect(path.posix  .join("foo", "bar", "baz")).to.equal("foo/bar/baz")
            expect(path.windows.join("foo", "bar", "baz")).to.equal("foo\\bar\\baz")

            expect(path.join("foo", "bar", "baz")).to.be.oneOf(
                {"foo/bar/baz", "foo\\bar\\baz"})
        end)
    end)
    describe(".parse()", function()
        it("splits a path into components", function()
            expect(path.posix.parse("/home/user/dir/file.tar.gz")).to.deep.equal(
                {root="/", dir="/home/user/dir", base="file.tar.gz", name="file.tar", ext=".gz"})
            expect(path.posix.parse("/.file")).to.deep.equal(
                {root="/", dir="/", base=".file", name=".file", ext=""})
            expect(path.posix.parse(".file.gz")).to.deep.equal(
                {root="", dir="", base=".file.gz", name=".file", ext=".gz"})

            expect(path.windows.parse("C:\\path\\dir\\file.txt")).to.deep.equal(
                {root="C:\\", dir="C:\\path\\dir", base="file.txt", name="file", ext=".txt"})
            expect(path.windows.parse("C:\\dir\\file.txt")).to.deep.equal(
                {root="C:\\", dir="C:\\dir", base="file.txt", name="file", ext=".txt"})
            expect(path.windows.parse("\\\\host\\root\\dir\\file.txt")).to.deep.equal(
                {root="\\\\host\\root\\", dir="\\\\host\\root\\dir", base="file.txt", name="file", ext=".txt"})
        end)
    end)
    -- path.resolve() is unfortunately not testable.
end)
