require("lunit")
--local re = require("re")

-- FIXME: delete this later
local P = require("parser")
local console = require("console")
local pRegex = require("re/parser")
console:log("%O", P.parse(P.finishOff(pRegex), "^さよち{2,12}$"))
console:log("%O", P.parse(P.finishOff(pRegex), "^さよち\\12a$"))
console:log("%O", P.parse(P.finishOff(pRegex), "^(さよ|ち)$"))
console:log("%O", P.parse(P.finishOff(pRegex), "^さ[よち]$"))
console:log("%O", P.parse(P.finishOff(pRegex), "^さ(?i)よち$"))
console:log("%O", P.parse(P.finishOff(pRegex), "^さ(?<よ>.ち)$"))
console:log("%O", P.parse(P.finishOff(pRegex), "\\bさ(?<よ>.ち)\\B"))
--error("ABORT NOW")
