require("lunit")
local SemVer = require("semver")

describe("SemVer", function()
    describe("constructor", function()
        it("can parse a simple semver string", function()
            local v = SemVer:new("1.20.333")
            expect(v).to.have.a.property("major",   1)
            expect(v).to.have.a.property("minor",  20)
            expect(v).to.have.a.property("patch", 333)
            expect(v).to.have.a.deep.property("preRelease", {})
            expect(v).to.have.a.deep.property("build"     , {})
        end)
        it("can parse a complex semver string", function()
            local v = SemVer:new("1.2.3-444.foo-bar+build1.0")
            expect(v).to.have.a.property("major", 1)
            expect(v).to.have.a.property("minor", 2)
            expect(v).to.have.a.property("patch", 3)
            expect(v).to.have.a.deep.property("preRelease", {444, "foo-bar"})
            expect(v).to.have.a.deep.property("build"     , {"build1", "0"})
        end)
    end)
    describe("tostring()", function()
        it("converts a SemVer object into the original string", function()
            expect(SemVer:new("1.20.333")).as("string").to.equal("1.20.333")
            expect(SemVer:new("1.2.3-444.foo-bar+build1.0")).as("string").to.equal("1.2.3-444.foo-bar+build1.0")
        end)
    end)
    describe("is equality comparable", function()
        local v1 = SemVer:new("1.0.0")
        local v2 = SemVer:new("1.0.0")
        expect(v1).to.equal(v2)

        -- Build metadata are ignored for comparison.
        local v1 = SemVer:new("1.0.0+build1")
        local v2 = SemVer:new("1.0.0+build2")
        expect(v1).to.equal(v2)
    end)
    describe("is ordered", function()
        local v1 = SemVer:new("1.0.0")
        local v2 = SemVer:new("1.2.0")
        expect(v1).to.below(v2)
    end)
end)
