require("lunit")
require("shim/utf8")

describe("utf8", function()
    describe(".char()", function()
        it("can handle non-SMP characters correctly🐈", function()
            expect(utf8.char(0x1F408)).to.equal("🐈")
        end)
    end)
    describe(".charpattern", function()
        it("is a string pattern that matches exactly one UTF-8 octet sequence", function()
            expect(utf8.charpattern).to.be.a("string")
                .that.satisfies(function(pat)
                    return string.match("🐈bc", pat) == "🐈"
                end)
        end)
    end)
    describe(".codes()", function()
        it("returns an iterator that iterates over code points in a UTF-8 string", function()
            local f, s, var = utf8.codes("a🐈c")
            expect(f).to.be.a("function")

            local pos, code = f(s, var)
            expect(pos).to.equal(1)
            expect(code).to.equal(0x61) -- a (61)

            local pos, code = f(s, pos)
            expect(pos).to.equal(2)
            expect(code).to.equal(0x01F408) -- 🐈 (F0 9F 90 88)

            local pos, code = f(s, pos)
            expect(pos).to.equal(6)
            expect(code).to.equal(0x63) -- c (63)

            local pos, code = f(s, pos)
            expect(pos).to.be.null()
            expect(code).to.be.null()
        end)
    end)
    describe(".codepoint()", function()
        it("returns code points for a byte range of UTF-8 string", function()
            local str = "a🐈c"
            expect({utf8.codepoint(str)}).to.deep.equal({0x61}) -- a
            expect({utf8.codepoint(str, 1, #str)}).to.deep.equal({0x61, 0x01F408, 0x63}) -- a🐈c
        end)
    end)
    describe(".len()", function()
        it("returns the number of code points in a byte range of UTF-8 string", function()
            expect(utf8.len("a🐈c")).to.equal(3)
        end)
    end)
    describe(".offset()", function()
        it("returns the byte offset where the character at offset i starts, if n == 0", function()
            expect(utf8.offset("a🐈c", 0, 3)).to.equal(2)
        end)
        it("returns the byte offset where the n-th character starts, if n ~= 0", function()
            expect(utf8.offset("a🐈c", 3)).to.equal(6)
        end)
    end)
end)
